---

- name: "Check existing global customHeaders."
  win_shell: "Get-WebConfigurationProperty \
  -pspath 'MACHINE/WEBROOT/APPHOST' \
  -filter 'system.webServer/httpProtocol/customHeaders' \
  -name ."
  register: iis_custom_headers_properties
  changed_when: false

- name: "Debug: show existing custom headers."
  debug:
    var: iis_custom_headers_properties
    verbosity: 1

- name: Include web configration property tasks.
  include: webconfigurationproperty.yml
  with_items:
    - "{{ iis_custom_headers | default(omit) }}"
  when: iis_custom_headers is defined
